---
title: "Code"
author: "Sjoerd Hochstenbach"
date: "7/9/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Libraries

```{r,echo=FALSE, results= 'hide', message=FALSE, warning=FALSE}
# the libraries we need
library(haven)
library(labelled)
library(bootnet)
library(ltm)
library(psych)
library(CliquePercolation)
library(igraph)
library(qgraph)
library(EGAnet)
library(sna)
library(grpreg)
library(SGL)
library(survival)
library(survminer)
library(tinytex)
library(knitr)
library(lubridate)
library(broom)
library(dplyr)
library(kableExtra)
```

Data Wrangling

```{r,echo=FALSE, results= 'hide', message=FALSE, warning=FALSE}
#We load the data and only include those patients that responded to the questionnaire
data = read_sav("profiles10000dataset_v7_31032022_Floor.sav")
dim(data) # we started with 14284 observations and 340 items
include_index=which(data$RESPONSE==1)
newdata=data[include_index,]
dim(newdata) #we now have 9774 observations on 340 items
newdata1 = newdata
names(newdata1) = as.character(var_label(newdata1))
newdata1 = remove_labels(newdata1) #dataframe with only label names
```

```{r,echo=FALSE, results= 'hide', message=FALSE, warning=FALSE}
# we make a dataframe with all depressive symptoms: 
all_symptoms = data.frame(newdata$HADS1, newdata$HADS2, newdata$HADS3, newdata$HADS4, newdata$HADS5, newdata$HADS6, newdata$HADS7,newdata$HADS8, newdata$HADS9, newdata$HADS10, newdata$HADS11, newdata$HADS12, newdata$HADS13, newdata$HADS14, newdata$Q21, newdata$Q22, newdata$Q23, newdata$Q24,newdata$FAS3, newdata$FAS6, newdata$FAS8)
# we extract the label for each item
mylabels = rep(NA, ncol(all_symptoms))
for(i in 1:ncol(all_symptoms)){
  mylabels[i] = attr(all_symptoms[, i], "label")
}
# we extract the number of missing observations for each item
missingobs = rep(NA, ncol(all_symptoms))
for(i in 1:ncol(all_symptoms)){
  missingobs[i] = sum(is.na(all_symptoms[ , i]))
}
# we make a table with all depressive symptoms, their labels, missing observations and total observations:
kable_styling(kable(data.frame("symptoms" = substr(colnames(all_symptoms), 9,30),  "labels" = mylabels, "missing observations" = missingobs, "total observations" = 9774- missingobs), caption = "All the items, their labels, missing observations and total observations"), latex_options = "HOLD_position")
```

```{r,echo=FALSE,  message=FALSE, warning=FALSE, results= 'hide'}
# vectors with item names and their longnames
names = c("HADS1", "HADS2", "HADS3", "HADS4", "HADS5", "HADS6", "HADS7", "HADS8", "HADS9", "HADS10", "HADS11","HADS12", "HADS13", "HADS14", "Q21", "Q22", "Q23", "Q24", "FAS3", "FAS6", "FAS8")
longnames = c("I feel tense or wound up", "I still enjoy the things I used to enjoy", "I get a sort of frightned feeling as if something awful is about to happen", "I can laugh and see the funny side of things", "Worrying thoughts go through my mind", "I feel cheerful", "I can sit at ease and feel relaxed", "I feel as if I am slowed down", "I get a sort of frightened feelink like 'butterflies' in the stomach", "I have lost interest in my appearance", "I feel restless, as if I have to be on the move", "I look forward with enjoyment to things", "I get sudden feelings of panic", "I can enjoy a good book or radio or TV program", "During the past week: Did you feel tense?", "During the past week: Did you worry?", "During the past week: Did you feel irritable?", "During the past week: Did you feel depressed?", "I don't do much during the day", "I have problems starting things", "I feel no desire to do anything")
```

```{r,echo=FALSE, message=FALSE, warning=FALSE}
#we firstl make a matrix and then a table with all sociodemographic characteristics
male=sum(na.omit(newdata1$Geslacht==1))
female=sum(na.omit(newdata1$Geslacht==2))
male.mean=round(mean(na.omit(newdata1$Geslacht==1))*100,2)
female.mean=round(mean(na.omit(newdata1$Geslacht==2))*100,2)
age.mean=round(mean(na.omit(newdata1$`Leeftijd ten tijde van diagnose`)),2)
age.sd=round(sd(na.omit(newdata1$`Leeftijd ten tijde van diagnose`)),2)
lower.ed=sum(na.omit(newdata1$`Indicate your highest education level.` == 1))
sec.ed.hs=sum(na.omit(newdata1$`Indicate your highest education level.`==2))
sec.ed.voc=sum(na.omit(newdata1$`Indicate your highest education level.`==3))
uni.higher.ed=sum(na.omit(newdata1$`Indicate your highest education level.`==4))
lower.ed.mean=mean(na.omit(newdata1$`Indicate your highest education level.` == 1))
sec.ed.hs.mean=mean(na.omit(newdata1$`Indicate your highest education level.`==2))
sec.ed.voc.mean=mean(na.omit(newdata1$`Indicate your highest education level.`==3))
uni.higher.ed.mean=mean(na.omit(newdata1$`Indicate your highest education level.`==4))
time.in.years=newdata1$`Tijd in dagen tussen diagnose en vragenlijstdatum (let op: niet invuldatum)`/365.25
time.in.years= na.omit(time.in.years)
time.4.6=sum(time.in.years>=4 & time.in.years<6)
time.6.8=sum(time.in.years>=6 & time.in.years<8)
time.8.10=sum(time.in.years>=8 & time.in.years<10)
time.10=sum(time.in.years>=10)
total.time=time.4.6+time.6.8+time.8.10+time.10
time.4.6.mean=round(time.4.6/total.time*100,2)
time.6.8.mean=round(time.6.8/total.time*100,2)
time.8.10.mean=round(time.8.10/total.time*100,2)
time.10.mean=round(time.10/total.time*100,2)
mymatrix = matrix("", nrow = 10, ncol = 3)
mymatrix[1,1] = "Sex"
mymatrix[1,2] = "Male/Female"
mymatrix[1,3] = paste(male, "/", female, " (", male.mean, "%/", female.mean, "%)", sep = "")
mymatrix[2,1] = "Age"
mymatrix[2,2] = "Year(SD)"
mymatrix[2,3] = paste(age.mean, " (", age.sd, ")", sep = "")
mymatrix[3,1] = "Time since diagnosis"
mymatrix[3,2] = ">= 4 and <6 years"
mymatrix[4,2] = ">= 6 and <8 years"
mymatrix[5,2] = ">= 8 and <10 years"
mymatrix[6,2] = ">= 10 years"
mymatrix[3,3] = paste(time.4.6, " (", time.4.6.mean , "%)", sep = "")
mymatrix[4,3] = paste(time.6.8, " (", time.6.8.mean , "%)", sep = "")
mymatrix[5,3] = paste(time.8.10, " (", time.8.10.mean , "%)", sep = "")
mymatrix[6,3] = paste(time.10, " (", time.10.mean , "%)", sep = "")
mymatrix[7,1] = "Education level"
mymatrix[7,2] = "Lower Education"
mymatrix[8,2] = "Secondary Education (High School)"
mymatrix[9,2] = "Secondary Education (Vocational)"
mymatrix[10,2] = "University, higher (vocational) education"
mymatrix[7,3] = paste(lower.ed, " (", round(lower.ed.mean*100,2), "%)", sep = "")
mymatrix[8,3] = paste(sec.ed.hs, " (", round(sec.ed.hs.mean*100,2), "%)", sep = "")
mymatrix[9,3] = paste(sec.ed.voc, " (", round(sec.ed.voc.mean*100,2), "%)", sep = "")
mymatrix[10,3] = paste(uni.higher.ed, " (", round(uni.higher.ed.mean*100,2), "%)", sep = "")
mydf= as.data.frame(mymatrix)
names(mydf) = NULL
kable_styling(kable(mydf, caption = "Sociodemographic Characteristics", booktab = T), latex_options = "HOLD_position")
```

```{r,echo=FALSE,  message=FALSE, warning=FALSE, results= "hide"}
#proportion missingness network analysis
sum(is.na(all_symptoms)) / (nrow(all_symptoms) * ncol(all_symptoms)) *100
```

```{r,echo=FALSE,  message=FALSE, warning=FALSE, results= "hide"}
# proportion missingness SGL:
100-4271/9774*100
```

```{r,echo=FALSE,  message=FALSE, warning=FALSE}
#we make a table with the missing data for each survival analysis
miss.df=data.frame("Analysis" = c("Cox Model 1", "Surv Plot and Log Rank for item HADS1", "Surv Plot and Log Rank for item HADS2", "Surv Plot and Log Rank for item Q23", "Surv Plot and Log Rank for item FAS3", "Cox Model 2"), "Observations Used" = c(4414,6859, 6851, 7298, 6721, 6744), "Observations Deleted" = c(5349, 2904, 2912, 2465, 3042, 2701), "Proportion Missingness" = c( paste(round(5349/(4414+5349)*100,2), "%", sep = ""), paste(round(2904/(2904+6859)*100,2), "%", sep = ""), paste(round(2912/(2912+6851)*100,2), "%", sep = ""), paste(round(2465/(2465+7298)*100,2), "%", sep = ""), paste(round(3042/(3042+6721)*100,2), "%", sep = ""), paste(round(2701/(2701+6744)*100,2), "%", sep = "")))
colnames(miss.df) = c("Analysis", "Observations Used", "Observations Deleted", "Proportion Missingness")
kable_styling(kable(miss.df, caption = "For every analysis: observations used, observations deleted and proportion missingness"), latex_options = "HOLD_position")
```

```{r,echo=FALSE , message=FALSE, warning=FALSE}
# we make a table with all the functions and packages that we use for our analysis
kable_styling(kable(data.frame("Function" = c("estimateNetwork", "centralityPlot", "qgraph", "as.igraph", "spinglass.community", "EGA", "cpThreshold", "cpAlgorithm", "SGL", "coxph", "survfit", "ggsurvplot", "survdiff"), "Package" = c("bootnet", "qgraph", "qgraph", "igraph", "igraph", "EGAnet", "CliquePercolation", "CliquePercolation", "SGL", "survival", "survival", "survminer", "survival"), "Description" = c("Estimate a network structure", "Centrality and Clustering plots", "Estimate a network structure", "Conversion to igraph", "Find communities in graphs via a spin-glass model", "Applies Exploratory Graph Analysis to find communities for Walktrap and Louvain", "Optimizing k and I for Clique Percolation Community Detection", "Clique Percolation Community Detection", "Fit a GLM with a combination of Lasso and Group Lasso Regularization", "Fit Proportional Hazards Regression Model", "Creates survival curves", "Drawing Survival Curves Using ggplot2", "Test Survival Curve Differences")), caption = "Functions and Packages", booktabs=TRUE ), font_size = 6, latex_options = "HOLD_position")
```

Simulation of some networks to show

```{r,echo=FALSE , message=FALSE, warning=FALSE, results='hide'}
# We simulate some precision matrices
input1 <- matrix(c(
0,1,1,
0,0,1,
0,0,0),3,3,byrow=TRUE)
colnames(input1) = c("i", "j", "k") ; rownames(input1) = c("i", "j", "k")  

input2 <- matrix(c(
0,1,2,
0,0,3,
0,0,0),3,3,byrow=TRUE)
colnames(input2) = c("i", "j", "k") ; rownames(input2) = c("i", "j", "k")  

input3 <- matrix(c(
0,1,1,
1,0,1,
1,1,0),3,3,byrow=TRUE)
colnames(input3) = c("i", "j", "k") ; rownames(input3) = c("i", "j", "k")  

input4 <- matrix(c(
0,1,-2,
1,0,3,
-2,3,0),3,3,byrow=TRUE)
colnames(input4) = c("i", "j", "k") ; rownames(input4) = c("i", "j", "k")  

print(input1); print(input2) ; print(input3); print(input4)
```

```{r,echo=FALSE , message=FALSE, warning=FALSE, fig.height= 3, fig.width=5, fig.cap= "Simulated Networks"}
par(mfrow = c(2,2))
# We show their corresponding networks
qgraph(input1, title = "1 = Directed , unweighted network") 
qgraph(input2, title = "2 = Directed, weighted network") 
qgraph(input3, title = "3 = Undirected, unweighted network") 
qgraph(input4, title = "4 = Undirected, weighted network") 
```


Estimate a network

```{r,echo=FALSE,  message=FALSE, warning=FALSE, fig.cap= "Network estimated with EBICglasso"}
#Network estimation
network = estimateNetwork(all_symptoms, default = "EBICglasso", labels = names, missing = "pairwise")
plot(network, layout = "spring", vsize = 6, cut = 0 , border.width = 1.5 , border.color = "black", nodeNames = longnames, legend.cex = 0.25)
```

```{r,echo=FALSE,  message=FALSE, warning=FALSE, fig.cap= "EBIC value for each Lambda"}
#how does the ebic value evolve for different values of lambda
df = data.frame("lambda" = network$results$lambda[1:40], "ebic" = network$results$ebic[1:40])
ggplot(data = df, aes(x = lambda, y = ebic)) +
  geom_point()+
  geom_line()+
  geom_vline(xintercept = network$results$lambda[19], colour = "red") +
  geom_hline(yintercept = network$results$ebic[19], colour = "red")+
  xlab("Lambda penalty")+
  ylab("EBIC value") +
  ggtitle("Corresponding EBIC values for the Lambda penalties")
```

```{r,echo=FALSE, results= 'hide', message=FALSE, warning=FALSE}
which.min(network$results$ebic) #which minimizes the EBIC
#the parameter values that minzimize EBIC:
network$results$ebic[19] ; network$results$lambda[19]
```

```{r,echo=FALSE, message=FALSE, warning=FALSE, fig.cap= "Centrality Plot"}
#we make a centrality plot for centrality indices betweenness, closeness and strength
centralityPlot(network, include = c("Betweenness", "Closeness", "Strength"), labels = network$labels)
```

Community Detection Algorithms

```{r,echo=FALSE, results='hide', message=FALSE, warning=FALSE, fig.show='hide'}
#Spinglass Algorithm
# we need a qgraph network in order to do the spinglass algorithm
cormatrix <- cor_auto(all_symptoms)
 
graph1<-qgraph(cormatrix, graph="glasso", layout="spring", sampleSize = nrow(newdata),
              vsize=6, cut=0, maximum=.45, border.width=1.5, labels = names, border.color = "black", title = "Depressed symptoms -4 communities", nodeNames = longnames, legend.cex = 0.25, missing = "pairwise")
```

```{r,echo=FALSE, message=FALSE, warning=FALSE}
#we estimate a Spinglass network for set.seed(123)
set.seed(123)
g = as.igraph(graph1, attributes=TRUE)
sgc <- spinglass.community(g)
kable_styling(kable(data.frame(names, sgc$membership), caption = "Community membership Spinglass", booktab = T), latex_options = "HOLD_position" )
```

```{r,echo=FALSE, results='hide', message=FALSE, warning=FALSE, eval=FALSE}
#we estimate 1000 different spinglass networks. We check how many times there were 4 communities or 5 communities
set.seed(123)
g = as.igraph(graph1, attributes=TRUE)
sgcs = replicate(1000, spinglass.community(g))
ncommunities = rep(NA,1000)
for(i in 1:1000){
  ncommunities[[i]]=length(sgcs[[i]]$csize)
}
med.communities = median(ncommunities)
med.communities
mean(ncommunities==4)*100 #98.2% of the results found 4 communities
mean(ncommunities==5)*100 #1.8% of the results found 5 communities
```

```{r,echo=FALSE,  message=FALSE, warning=FALSE, fig.cap= "Walktrap Network"}
#We estimate a Walktrap network
colnames(all_symptoms) = names
my.ega1 =EGA(all_symptoms, algorithm = "walktrap", model = "glasso", plot.EGA = TRUE,  missing = "pairwiseEG")
#my.ega1$wc
```

```{r,echo=FALSE,  message=FALSE, warning=FALSE, fig.cap="Louvain Network"}
#We estimate a Louvain network
my.ega2 = EGA(all_symptoms, algorithm = "louvain", model = "glasso", plot.EGA = TRUE, missing = "pairwise")
```

```{r,echo=FALSE, results = 'hide', message=FALSE, warning=FALSE}
#we let the threshold I vary from 0.2 until 0.01 and check which threshold is optimal
thresholds = cpThreshold(graph1, method = "weighted", k.range = 3, I.range = c(seq(0.2, 0.01, by = -0.01)), threshold = c("largest.components.ratio", "chi"))
names(thresholds) = c("k", "Intensity", "N Communities", "N Isolated Nodes", "Ratio Threshold", "Chi Threshold")
```

```{r,echo=FALSE,  message=FALSE, warning=FALSE}
# we show the table
kable_styling(kable(head(thresholds,12), caption = "Optimizing k And I For Clique Percolation Community Detection", booktab = T), latex_options = "HOLD_position")
```

```{r,echo=FALSE, message=FALSE, warning=FALSE, fig.cap= "CPM Network"}
#run clique percolation algorithm with specific k =3 and I =0.13
cp = cpAlgorithm(graph1, k = 3, method = "weighted", I = 0.16)
results = cpColoredGraph(graph1, list.of.communities = cp$list.of.communities.labels, layout = "spring", edge.labels = TRUE, nodeNames = longnames, legend.cex= 0.25, title = "Communities based on Clique Percolation")
```

```{r,echo=FALSE,  results='hide', message=FALSE, warning=FALSE}
# we show which items loaded in which community for every community detection algorithm
df= data.frame("spinglass" = c(sgc$membership, "ncom = 4"), "walktrap" = c(my.ega1$wc,4), "louvain" = c(my.ega2$wc ,5), "CPM" = c(1,2,1,2,1,NA,3,"2 and 4", NA, NA, 3, 2, 1, 3, 1,1,1,1, 4, 4, 4, 4))
kable_styling(kable(df, caption = "Community Detection Algorithms results", booktab = T),latex_options = "HOLD_position")
```

```{r,echo=FALSE,  message=FALSE, warning=FALSE}
#To ease interpretation, we show a table with consistent coding.
df[c(1,3,5,13),] = c(1,1,1,1)
df[c(2,4,12), ] = c(2,2,2,2)
df[15:18, ] = c(3,3,3,3)
df[19:21, ] = c(4,4,4,4)
df[8, ] = c(1,4,4,4)
df[6, ] = c(4,2,3,NA)
df[7,] = c(2,1,5,5)
df[9,] = c(3,1,1,NA)
df[10,] = c(1,2,2,NA)
df[11,] = c(1,1,5,5)
df[14,] = c(2,2,5,5)
df = df[-22, ]
df$group = c(1,2,1,2,1,NA,NA,4,NA,NA,NA,2,1,NA,rep(3,4), rep(4,3))
kable_styling(kable(df, caption = "Community Detection Algorithms results", booktab = T), latex_options = "HOLD_position")
```

```{r,echo=FALSE,  message=FALSE, warning=FALSE}
# we assign the items to their communities
comm.df = data.frame("Community 1" = c("HADS1","HADS3", "HADS5", "HADS13", "", ""), "Community 2" = c("HADS2", "HADS4", "HADS12", "", "", ""), "Community 3" = c("Q21", "Q22", "Q23", "Q24", "", ""), "Community 4" = c("FAS3", "FAS6", "FAS8", "HADS8", "", ""), "No Community" = c("HADS6", "HADS7", "HADS9", "HADS10", "HADS11", "HADS14"))
colnames(comm.df) = c("Community 1", "Community 2", "Community 3", "Community 4", "No Community")
kable_styling(kable(comm.df, caption = "Communities and their items"), latex_options = "HOLD_position")
```

```{r,echo=FALSE,  message=FALSE, warning=FALSE, fig.cap= "Network with communities found by algorithms"}
#we plot a network which show the communities according to the community detection algorithms
all_symptoms = all_symptoms[, c(1,3,5,13,2,4,12,15:21,8)] # we continue with only the items that belonged to a community
network = estimateNetwork(all_symptoms, default = "EBICglasso", labels = names[c(1,3,5,13,2,4,12,15:21,8)], missing = "pairwise")
gr1 = list("Negative Affect" = c(1:4), "Consummatory Anhedonia" = c(5:7), "Recent Negative Affect" = c(8:11), "Motivational Anhedonia" = c(12:15))
plot(network, layout = "spring", vsize = 5.5, cut = 0 , border.width = 1.5, border.color = "black", title = "Communities according to all algorithms", nodeNames = longnames[c(1,3,5,13,2,4,12,15:21,8)], legend.cex = 0.22, groups = gr1)
```

SGL

```{r,echo=FALSE, results=' hide' , message=FALSE, warning=FALSE}
#Time variables:
newdata$diagn_date = ymd(newdata$datumverz) - newdata$Time_since_diagnosis #we make a variable representing the date of diagnosis
newdata$vitstat_date = ymd(newdata$diagn_date) + newdata$Vitfup #we make a variable representing the date on which the vital status was measured
newdata$invul_date = ymd(newdata$vitstat_date) - newdata$dgn_overleden #we make a variable representing the date on which the patient filled in the questionnaire
newdata$tijdsvariabele = ymd(newdata$vitstat_date) - ymd(newdata$datumverz) #we make a time variable for survivors counting the days from sending the questionnaire until measurement of vital status
sterfindex= which(newdata$vit_stat==1) #an index for the people that died
newdata$tijdsvariabele[sterfindex] = newdata$dgn_overleden[sterfindex] #we adjust the time variable for the people that died by using our sterfindex in the variable dgn_overleden
```

```{r,echo=FALSE, results=' hide' , message=FALSE, warning=FALSE}
#some more time variables
time = as.numeric(newdata$tijdsvariabele)
time.transformed = time/30.5 #on average there are about 30.5 days per month
status = newdata$vit_stat
index.na = which(is.na(status)) #which patients have missing value for the status variable? We have to exclude them. Also for the other variables:
time.transformed = time.transformed[-index.na]
status = status[-index.na]
age_quest = newdata$Age_quest[-index.na]
```

```{r,echo=FALSE, results=' hide' , message=FALSE, warning=FALSE}
# we fit the SGL
cox.df= data.frame(all_symptoms[-index.na,], time.transformed, status, age_quest)
sgl.df = na.omit(cox.df) #we have to remove the na values to make this work
data = list(x = sgl.df[, 1:15], time = sgl.df$time.transformed, status = sgl.df$status)
index = c(rep(1,4), rep(2,3), rep(3,4), rep(4,4))
fit = SGL(data = data, index=index, type = "cox")
#fit
```

```{r,echo=FALSE , message=FALSE, warning=FALSE, fig.cap="Total number of nonzero parameters for each Lambda"}
# we show the number of nonzero parameters for each lambda
df = data.frame(x = fit$lambdas, y = c(0,3, rep(5,11), 6, 7, 7, rep(8,4)))
ggplot(df, aes(x = x, y =y)) +
  geom_line()+
  xlab("lambda") +
  ylab("number of nonzero parameters")
```

```{r,echo=FALSE , results='hide' ,message=FALSE, warning=FALSE}
#we make a dataframe showing the results of the SGL
betas = as.matrix(fit$beta)
betas = t(betas)
colnames(betas) = colnames(cox.df[, 1:15])
rownames(betas) = round(fit$lambdas,6)
community = c(rep("negative affect", 4), rep("consummatory anhedonia", 3), rep("(recent) negative affect", 4), rep("motivational anhedonia", 4))
betas = rbind(community, betas)
```

```{r,echo=FALSE , message=FALSE, warning=FALSE, fig.cap= " Number of nonzero parameters for every lambda for every community"}
#we plot the number of nonzero parameters for every lambda for every community
df = data.frame(x = fit$lambdas, "consummatory anhedonia" = c(0, 1, rep(3, 18)), "motivational anhedonia" = c(0, rep(2,19)), "negative affect" = c(rep(0,13), rep(1,7)), "recent negative affect" = c(rep(0, 14), rep(1,2), rep(2,4)))
ggplot()+
  geom_step(data = df, aes(y = consummatory.anhedonia, x= x, colour = "consummatory anhedonia"))+
  geom_point(shape=6, size = 2, data = df, aes(y = consummatory.anhedonia, x= x, colour = "consummatory anhedonia"))+
  geom_step(data = df, aes(y = motivational.anhedonia, x= x, colour = "motivational anhedonia"))+
  geom_point(shape = 2, size = 1.5, data = df, aes(y = motivational.anhedonia, x= x, colour = "motivational anhedonia"))+
  geom_step(data = df, aes(y = negative.affect, x= x, colour = "negative affect"))+
  geom_point(shape = 7, size = 2, data = df, aes(y = negative.affect, x= x, colour = "negative affect"))+
   geom_step(data = df, aes(y = recent.negative.affect, x= x, colour = "recent negative affect"))+
  geom_point(data = df, aes(y = recent.negative.affect, x= x, colour = "recent negative affect"))+
  scale_color_manual(name = "Community", values = c("consummatory anhedonia" = "blue", "motivational anhedonia" = "purple", "negative affect" = "red", "recent negative affect" = "orange"))+
  labs(y = "Number of nonzero parameters",
       x = "Lambda",
       title = "Number of nonzero parameters for every lambda for every community")
```

```{r,echo=FALSE , message=FALSE, warning=FALSE}
#we show the model with lambda =0.000385
lambda.000385= as.data.frame(t(rbind(community, betas[16,]))) #16 instead of 15 because first row is communities
colnames(lambda.000385) = c("community", "effect")
kable_styling(kable(lambda.000385, caption = "results for SGL model with lambda = 0.000385", booktab = T), latex_options = "HOLD_position")
```

Survival Analysis

```{r,echo=FALSE, message=FALSE, warning=FALSE, results= "hide"}
# a cox proportional hazards model for the representing variables of the communities
coxph(Surv(time.transformed, status)~ HADS1 + HADS2+ Q23 + FAS3 + age_quest, data = cox.df)
```

```{r}
# the corresponding table
kable_styling(kable(data.frame("item" = c("HADS1", "HADS2", "Q23", "FAS3", "Age"), "coef" = c(0.04298, 0.18380, 0.08189, 0.22313, 0.06482), "exp(coef)" = c(1.04392, 1.20177, 1.08533, 1.24998, 1.06696), "se(coef" = c(0.03745, 0.03499, 0.03903, 0.02255, 0.00266), "z" = c(1.148, 5.252, 2.098, 9.896, 24.369), "p" = c(0.2511, 1.5e-07, 0.0359, "<2e-16", "<2e-16")), caption = "Cox Model 1, n =4414, number of events = 1787 (5349 observations deleted due to missingness"), latex_options = "HOLD_position")
```

```{r,echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
# we make our fits for the survival curves
fit_HADS1 = survfit(Surv(time.transformed, status) ~ HADS1 , data = cox.df)
fit_Q23 = survfit(Surv(time.transformed, status) ~ Q23 , data = cox.df)
fit_FAS3 = survfit(Surv(time.transformed, status) ~ FAS3 , data = cox.df)
fit_HADS2 = survfit(Surv(time.transformed, status) ~ HADS2 , data = cox.df)
```

```{r,echo=FALSE , message=FALSE, warning=FALSE}
#we plot the survival curve for HADS1
ggsurv1 = ggsurvplot(fit_HADS1, legend.labs = c("0 = Most of the time", "1 = A lot of the time", "2 = From time to time, occasionally","3 = Not at all"), legend.title = "HADS1: I feel tense or
'wound up' (negative affect)") 
ggsurv1$plot +
  theme(legend.text = element_text(size = 7), legend.title = element_text(size = 7))
```

```{r,echo=FALSE , message=FALSE, warning=FALSE, results="hide"}
#Log rank for HADS1
survdiff(Surv(time.transformed, status) ~ HADS1, data = cox.df)
```

```{r,echo=FALSE , message=FALSE, warning=FALSE}
# the corresponding table
HADS1 = data.frame("Response" = c("HADS1=0", "HADS1=1", "HADS1=2","HADS1=3"), "N" = c(224,618,3695,2322), "Observed" = c(111,266,1441,943), "Expected" = c(80.5,234.6,1505.7,940.2), "(O-E)^2/E" = c(11.587, 4.196, 2.782, 0.00838), "(O-E)^2/V" = c(11.938, 4.587, 6.120, 0.013))
colnames(HADS1) = c("Response", "N", "Observed", "Expected", "(O-E)^2/E", "(O-E)^2/V")
kable_styling(kable(HADS1, caption = "Log Rank test for item HADS1, n = 6859, 2904 observations deleted due to missingness, Chisq = 18.6 on 3 degrees of freedom, p= 3e-04"), latex_options = "HOLD_position" )
```

```{r,echo=FALSE , message=FALSE, warning=FALSE}
# the survival curve for HADS2
ggsurv2 = ggsurvplot(fit_HADS2, legend.labs = c("0 = Definitely as much", "1 = Not quite so much", "2 = Only a little",
"3 = Hardly at all"), legend.title = "HADS2: I still enjoy
the things I used to enjoy
(consummatory anhedonia)")
ggsurv2$plot +
  theme(legend.text = element_text(size = 7), legend.title = element_text(size = 7))
```

```{r,echo=FALSE , message=FALSE, warning=FALSE, results="hide"}
#log rank test for HADS2
survdiff(Surv(time.transformed, status) ~ HADS2, data = cox.df)
```

```{r,echo=FALSE , message=FALSE, warning=FALSE}
# the corresponding table for HADS2
HADS2 = data.frame("Response" = c("HADS2=0", "HADS2=1", "HADS2=2","HADS2=3"), "N" = c(3789,2235,678,149), "Observed" = c(1197,1078,385,97), "Expected" = c(1633.2, 852.7, 227.4, 43.7), "(O-E)^2/E" = c(116.5, 59.5, 109.2, 64.9), "(O-E)^2/V" = c(286.5, 86.3, 119.1, 66.0))
colnames(HADS2) = c("Response", "N", "Observed", "Expected", "(O-E)^2/E", "(O-E)^2/V")
kable_styling(kable(HADS2, caption = "Log Rank test for item HADS2, n = 6851, 2912 observations deleted due to missingness, Chisq = 351 on 3 degrees of freedom, p= <2e-16"), latex_options = "HOLD_position" )
```

```{r,echo=FALSE , message=FALSE, warning=FALSE}
# survival curve for Q23
ggsurv3 = ggsurvplot(fit_Q23, legend.labs = c("1 = Not at all", "2 = A little", "3 = Quite a bit", "4 = Very much"), legend.title = "Q23: Did you feel irritable?
(recent negative affect")
ggsurv3$plot +
  theme(legend.text = element_text(size = 7), legend.title = element_text(size = 7))
```

```{r,echo=FALSE , message=FALSE, warning=FALSE, results="hide"}
#Log rank test Q23
survdiff(Surv(time.transformed, status) ~ Q23, data = cox.df)
```

```{r,echo=FALSE , message=FALSE, warning=FALSE}
#corresponding table for Q23
Q23 = data.frame("Response" = c("Q23=1", "Q23=2", "Q23=3","Q23=4"), "N" = c(4986,1775,435,102), "Observed" = c(1709,706,181,39), "Expected" = c(1827,621.9,149.6,36.5), "(O-E)^2/E" = c(7.620,11.376,6.676, 0.173), "(O-E)^2/V" = c(24.860, 14.894, 6.974, 0.175))
colnames(Q23) = c("Response", "N", "Observed", "Expected", "(O-E)^2/E", "(O-E)^2/V")
kable_styling(kable(Q23, caption = "Log Rank test for item Q23, n = 7298, 2465 observations deleted due to missingness, Chisq = 25.8 on 3 degrees of freedom, p= 1e-05"), latex_options = "HOLD_position" )
```

```{r,echo=FALSE , message=FALSE, warning=FALSE}
#Survival curve FAS3
ggsurv4= ggsurvplot(fit_FAS3, legend.labs = c("1 = Never", "2 = Sometimes", "3 = Regularly", "4 = Often", "5= Always"), legend.title = "FAS3: I don't do much during the day (motivational anhedonia")
ggsurv4$plot +
  theme(legend.text = element_text(size = 7), legend.title = element_text(size = 7))
```

```{r,echo=FALSE , message=FALSE, warning=FALSE, results="hide"}
#log rank FAS3
survdiff(Surv(time.transformed, status) ~ FAS3, data = cox.df)
```

```{r,echo=FALSE , message=FALSE, warning=FALSE}
#corresponding table FAS3
FAS3 = data.frame("Response" = c("FAS3=1", "FAS3=2", "FAS3=3","FAS3=4", "FAS3=5"), "N" = c(1953,2622,1122,756,268), "Observed" = c(604,970,577,426,172), "Expected" = c(868,1122,418.4,261.2,79.3), "(O-E)^2/E" = c(80.3,20.6,60.1,103.9,108.4), "(O-E)^2/V" = c(117.5, 34.8, 71.0, 114.9, 111.7))
colnames(FAS3) = c("Response", "N", "Observed", "Expected", "(O-E)^2/E", "(O-E)^2/V")
kable_styling(kable(FAS3, caption = "Log Rank test for item FAS3, n = 6721, 3042 observations deleted due to missingness, Chisq = 374 on 3 degrees of freedom, p= <2e-16"), latex_options = "HOLD_position" )
```

```{r,echo=FALSE , message=FALSE, warning=FALSE, results="hide"}
#cox proportional hazards model isolated nodes
newdata = newdata[-index.na, ] #we use the same index as before
mydf = data.frame(time.transformed, status, newdata$HADS6, newdata$HADS7, newdata$HADS9, newdata$HADS10, newdata$HADS11, newdata$HADS14, age_quest)
colnames(mydf) = c("time, status", "HADS6", "HADS7", "HADS9", "HADS10", "HADS11", "HADS14")
coxph(Surv(time.transformed, status) ~ HADS7+ HADS9 + HADS10 +HADS11 + HADS14+ age_quest , data = mydf)
```

```{r,echo=FALSE , message=FALSE, warning=FALSE}
#corresponding table
kable_styling(kable(data.frame("item" = c("HADS7", "HADS9", "HADS10", "HADS11", "HADS14", "Age"), "coef" = c(-0.073, -0.022, 0.057, -0.175, -0.013, 0.069), "exp(coef)" = c(0.929, 0.978, 1.059, 0.839, 0.987, 1.071), "se(coef" = c(0.022, 0.027, 0.032, 0.026, 0.022, 0.002), "z" = c(-3.275, -0.805, 1.755, -6.605, -0.600, 30.583), "p" = c(0.00106, 0.42087,0.07926,3.98e-11, 0.54871, "<2e-16")), caption = "Cox Model 2, n =6744, number of events = 2701 (3019 observations deleted due to missingness"), latex_options = "HOLD_position")
```



